server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/helix_fish_uaa?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: Win2008@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 60000
      connection-test-query: SELECT 1
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true #Hibernate操作时显示真实的SQL, 缺省：false
    properties:
      hibernate:
        show_sql: true #日志记录执行的SQL
        formate_sql: true #日志记录执行的SQL